service: votes

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-2
  environment:
    DYNAMO_RESOURCE: ${env:DYNAMO_RESOURCE}
  iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource: "${self:provider.environment.DYNAMO_RESOURCE}"

functions:
  list:
    handler: handlers/list.default
    events:
      - http:
          path: votes
          method: get
          cors: true
  create:
    handler: handlers/create.default
    events:
      - http:
          path: votes
          method: post
          cors: true
  delete:
    handler: handlers/delete.default
    events:
      - http:
          path: votes/{user_id}/{idea_id}
          method: delete
          cors: true
